sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.1 - Drop tables.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.2 - Create tables.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.3 - Insert real data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.4 - Insert fake data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.5 - Create table ChassisType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.6 - Populate ChassisType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.7 - Create table VehicleType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.8 - Create table VehicleState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.0.9 - Populate VehicleState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.0 - Create table Vehicle.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.1 - Create table AuditType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.2 - Create table Audit.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.3 - Populate table AuditType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.4 - Create table ItemType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.5 - Populate table ItemType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.6 - Add column IdItemType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.7 - Update Role.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.8 - Update NotificationType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.1.9 - Add column IsDeleted.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.0 - Remove previous audit columns.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.1 - Add columns in Vehicle.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.2 - Add column PriceSign.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.3 - Add column IsEnabled.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.4 - Create table StockSettingType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.5 - Populate table StockSettingType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.6 - Add column IdStockSettingType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.7 - Add column Pending.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.8 - Change column Description.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.2.9 - Create table TireState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.0 - Populate table TireState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.1 - Create table Tire.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.2 - Change columns in Vehicle.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.3 - Create table Document.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.4 - Create table VehicleDocumentation.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.5 - Update VehicleState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.6 - Create table VehicleTire.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.7 - Rename column in VehicleType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.7.1 - Rename column in VehicleType - Fake Data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.8 - Add column in ChassisType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.3.9 - Update Tires in ChassisType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.0 - Create table ChassisTypeCoords.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.1 - Update ChassisTypeCoords.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.2 - Add column in ItemArea.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.3 - Create table ReportState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.4 - Populate table ReportState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.5 - Create table VehicleActivityReport.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.6 - Create table VehicleActivity.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.7 - Create table VehicleTireActivity.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.8 - Add column in VehicleActivity.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.4.9 - Add column in VehicleTireActivity.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.0 - Drop columns from Activity tables.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.0.1 - Drop columns from Activity tables - Fake Data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.1 - Change columns in Activity tables.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.2 - Add Description to ChassisType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.3 - Create table TireBrand.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.4 - Create table TireSize.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.5 - Create table TireType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.6 - Add new colums in Tire.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.7 - Update ChassisTypeCoords.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.8 - Add new record in StockMovementType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.5.9 - Add IdItemArea in Tire.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.0 - Remove IdItem from Tire.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.1 - Create table TireTracking.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.2 - Create table Employee.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.2.1 - Create table Employee - Fake Data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.3 - Create table MaintenanceMotive.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.3.1 - Create table MaintenanceMotive - Fake Data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.4 - Create table MaintenanceTask.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.5 - Create table MaintenanceOrder.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.5.1 - Create table MaintenanceOrder - Fake Data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.6 - Create table MaintenanceOrderMotive.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.7 - Add CreationDate in Tire.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.8 - Add Duration in MaintenanceTask.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.8.1 - Add Duration in MaintenanceTask - Fake Data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.8.2 - Add Duration in MaintenanceTask - Real Data.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.6.9 - Create table TireStateHistory.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.0 - Add IdRequestingEmployee in MaintenanceOrder.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.1 - Create table MaintenanceOrderTask.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.2 - Create table MaintenanceOrderItem.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.3 - Add new record in StockMovementType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.4 - Create table MaintenanceOrderState.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.5 - Add new column in MaintenanceOrder.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.6 - Add new role in Role.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.7 - Add new record in MaintenanceTask.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.8 - Create new table MaintenanceTaskAlertType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.7.9 - Add new column in MaintenanceTask.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.8.0 - Add new column in Notification.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.8.1 - Add new records in NotificationType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.8.2 - Create new table MaintenanceOrderTireReplacement.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.8.3 - Create new table MaintenanceTaskVehicleType.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.8.4 - Create new table MaintenanceTaskVehicleArea.sql"
sqlcmd -S %1 -d %2 -W -i "ITrack 1.0.8.5 - Alter column in MaintenanceOrder.sql"
pause